server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mydb"
    username: root
    password: truongdz002
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "spGPoGS+DN4lVBUpComU0Tffhvv7Nmu/M2aYHhn4tlzR+llX0zZLmJQ9go+0VOXv"
